services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./components/compass-api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - JWT_SECRET_KEY=thisisasecretkey
      - DEFAULT_ADMIN_PASSWORD=admin

  ui:
    build:
      context: ./components/compass-ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  mongo-data:
