@baseUrl = http://localhost:8000/api
@adminToken = ''
@userToken = ''

### Login as admin
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin123

### Store admin token
@adminToken = {{login.response.body.access_token}}

### Get comments for a solution
GET {{baseUrl}}/comments/solution/example-solution
Authorization: Bearer {{adminToken}}

### Create a comment
POST {{baseUrl}}/comments
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "object_type": "solution",
  "object_id": "example-solution",
  "content": "This is a test comment",
  "adoption_status": "CURRENT_USER"
}

### Reply to a comment
POST {{baseUrl}}/comments
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "object_type": "solution",
  "object_id": "example-solution",
  "content": "This is a reply",
  "parent_id": "64a7b3c9d2e1f0a5b6c7d8e9"
}

### Update a comment
PUT {{baseUrl}}/comments/64a7b3c9d2e1f0a5b6c7d8e9
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "content": "Updated comment content"
}

### Delete a comment
DELETE {{baseUrl}}/comments/64a7b3c9d2e1f0a5b6c7d8e9
Authorization: Bearer {{adminToken}}

### Get comment statistics for a solution
GET {{baseUrl}}/comments/stats/solution/example-solution
Authorization: Bearer {{adminToken}} 